DROP TABLE BOARD_T;
CREATE TABLE BOARD_T
(
    BOARD_NO    NUMBER              NOT NULL PRIMARY KEY,
    WRITER      VARCHAR2(50 BYTE),
    TITLE       VARCHAR2(1000 BYTE) NOT NULL,
    CONTENTS    VARCHAR2(4000 BYTE),
    CREATED_AT  TIMESTAMP,
    MODIFIED_AT TIMESTAMP
);
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

INSERT INTO BOARD_T VALUES(BOARD_SEQ.NEXTVAL, '작성자1', '제목1', '내용1', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO BOARD_T VALUES(BOARD_SEQ.NEXTVAL, '작성자2', '제목2', '내용2', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO BOARD_T VALUES(BOARD_SEQ.NEXTVAL, '작성자3', '제목3', '내용3', SYSTIMESTAMP, SYSTIMESTAMP);
COMMIT;