DROP SEQUENCE CBC_SEQ;
CREATE SEQUENCE CBC_SEQ NOCACHE;

DROP TABLE CBC_T;
CREATE TABLE CBC_T (
    CBC_NO      NUMBER              NOT NULL,
    EDITOR      VARCHAR2(50 BYTE),
    TITLE       VARCHAR2(50 BYTE)   NOT NULL,
    CONTENTS    VARCHAR2(1000 BYTE),
    CREATED_AT  DATE,
    MODIFIED_AT DATE,
    CONSTRAINT  PK_CBC PRIMARY KEY(CBC_NO)
);

INSERT INTO CBC_T VALUES(CBC_SEQ.NEXTVAL, '작성자', '제목', '내용', SYSDATE, SYSDATE);
COMMIT;